services:
  client:
    container_name: dev_client
    build: ./Client
    image: client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./Client
        target: /code
    command: [ "http-server" ]
  server:
    container_name: dev_server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=anonpostspass
      - PGDATABASE=anonposts
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=anonposts
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=anonpostspass
volumes:
  dbdata:
networks: 
  default:
    name: server
