services:
  server:
    container_name: test_server
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=anonpostspass
      - PGDATABASE=anonposts_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=anonposts_test
      - POSTGRES_PASSWORD=anonpostspass
volumes:
  test_db:
networks: 
  default:
    name: test
